global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager@example.com'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'environment']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 10s
      repeat_interval: 1h
    - match:
        environment: preprod
      receiver: 'preprod-alerts'
      group_wait: 15s
      repeat_interval: 2h

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@example.com'
        headers:
          Subject: '[CRITIQUE] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        html: |
          {{ range .Alerts }}
          <strong>Alerte :</strong> {{ .Annotations.summary }}<br>
          <em>Description :</em> {{ .Annotations.description }}<br>
          <em>Environnement :</em> {{ .Labels.environment }}<br>
          <em>Sévérité :</em> {{ .Labels.severity }}<br>
          <em>Statut :</em> {{ .Status }}<br>
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: 'Alerte Critique - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Environnement: {{ .Labels.environment }}
          {{ end }}
        color: 'danger'

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@example.com'
        headers:
          Subject: '[ATTENTION] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        html: |
          {{ range .Alerts }}
          <strong>Alerte :</strong> {{ .Annotations.summary }}<br>
          <em>Description :</em> {{ .Annotations.description }}<br>
          <em>Environnement :</em> {{ .Labels.environment }}<br>
          <em>Sévérité :</em> {{ .Labels.severity }}<br>
          {{ end }}

  - name: 'critical-alerts'
    slack_configs:        
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts-devops'
        title: ' Alerte Critique - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Environnement: {{ .Labels.environment }}
          {{ end }}
        color: 'danger'

  - name: 'preprod-alerts'
    email_configs:
      - to: 'dev-team@example.com'
        headers:
          Subject: '[PREPROD] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        html: |
          {{ range .Alerts }}
          <strong>[Préproduction]</strong><br>
          <strong>{{ .Annotations.summary }}</strong><br>
          {{ .Annotations.description }}<br>
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'environment']

  - source_match:
      alertname: 'PodNotReady'
    target_match:
      alertname: 'PodCrashLooping'
    equal: ['pod', 'namespace']