groups:
- name: infrastructure.rules
  rules:
  - alert: PodCrashLooping
    expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
    for: 5m
    labels:
      severity: warning
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "Pod {{ $labels.pod }} is crash looping"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently"

  - alert: PodNotReady
    expr: kube_pod_status_ready{condition="false"} == 1
    for: 10m
    labels:
      severity: critical
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "Pod {{ $labels.pod }} not ready"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been not ready for more than 10 minutes"

  - alert: HighCPUUsage
    expr: avg by (namespace, pod) (rate(container_cpu_usage_seconds_total{namespace=~"default|preprod"}[5m]) * 100) > 80
    for: 5m
    labels:
      severity: warning
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "High CPU usage detected"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has CPU usage above 80% for more than 5 minutes"

  - alert: HighMemoryUsage
    expr: avg by (namespace, pod) (container_memory_usage_bytes{namespace=~"default|preprod"} / container_spec_memory_limit_bytes{namespace=~"default|preprod"} * 100) > 90
    for: 5m
    labels:
      severity: critical
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "High memory usage detected"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has memory usage above 90% for more than 5 minutes"

  - alert: MySQLDown
    expr: up{job="kubernetes-pods", pod=~"mysql.*"} == 0
    for: 1m
    labels:
      severity: critical
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "MySQL database is down"
      description: "MySQL pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is down"

  - alert: WordPressDown
    expr: up{job="kubernetes-pods", pod=~"wordpress.*"} == 0
    for: 2m
    labels:
      severity: critical
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "WordPress application is down"
      description: "WordPress pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is down"

  - alert: PersistentVolumeUsageHigh
    expr: (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Persistent volume usage is high"
      description: "Persistent volume {{ $labels.persistentvolumeclaim }} usage is above 85%"

  - alert: NodeDiskSpaceHigh
    expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Node disk space is critically low"
      description: "Node {{ $labels.instance }} has less than 15% disk space available"

  - alert: NodeMemoryHigh
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Node memory usage is critically high"
      description: "Node {{ $labels.instance }} has less than 10% memory available"

- name: application.rules
  rules:
  - alert: HighErrorRate
    expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) / rate(nginx_http_requests_total[5m]) * 100 > 5
    for: 5m
    labels:
      severity: warning
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 5% for more than 5 minutes in {{ $labels.namespace }}"

  - alert: SlowResponseTime
    expr: histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket[5m])) > 2
    for: 5m
    labels:
      severity: warning
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "Slow response time detected"
      description: "95th percentile response time is above 2 seconds in {{ $labels.namespace }}"

- name: database.rules
  rules:
  - alert: MySQLConnectionsHigh
    expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100 > 80
    for: 5m
    labels:
      severity: warning
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "MySQL connections usage is high"
      description: "MySQL connections usage is above 80% in {{ $labels.namespace }}"

  - alert: MySQLSlowQueries
    expr: rate(mysql_global_status_slow_queries[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
      environment: "{{ $labels.namespace }}"
    annotations:
      summary: "MySQL slow queries detected"
      description: "MySQL slow queries rate is above 0.1 per second in {{ $labels.namespace }}"