apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Correction: Email valide nécessaire (vérifiez l'orthographe de gmail)
    email: bigmangt103@gmail.com  # ".com" au lieu de ".gamil"
    
    # Production (pour vrais certificats)
    server: https://acme-v02.api.letsencrypt.org/directory
    
    privateKeySecretRef:
      name: letsencrypt-private-key

    solvers:
    - http01:
        ingress:
          class: traefik
          # Ajouts recommandés :
          podTemplate:
            spec:
              nodeSelector:
                kubernetes.io/os: linux


