community:
  enabled: true

monitoringPasscode: "SecurePass123!"

postgresql:
  enabled: false

externalDatabase:
  host: postgres.sonarqube.svc.cluster.local
  port: 5432
  user: sonarqube_user
  password: "sonarqube123"
  database: sonarqube
  type: postgresql

sonarqube:
  jdbcOverwrite:
    enable: true
    url: "jdbc:postgresql://postgres.sonarqube.svc.cluster.local:5432/sonarqube"
    username: "sonarqube_user"
    password: "sonarqube123"

extraInitContainers:
  - name: check-db
    image: busybox:1.35
    command:
      - sh
      - -c
      - |
        echo "Waiting for PostgreSQL to be ready...";
        until nc -z postgres.sonarqube.svc.cluster.local 5432; do
          echo "PostgreSQL is unavailable - sleeping";
          sleep 2;
        done;
        echo "PostgreSQL is up - continuing.";

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 1Gi
    cpu: 500m
