---
name: Setup SonarQube Infrastructure

on:
  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/workflows/sonarqube-setup.yaml"]

env:
  PROJECT_ID: primordial-port-462408-q7
  CLUSTER_NAME: primordial-port-462408-q7-gke-cluster
  CLUSTER_REGION: europe-west9

jobs:
  deploy-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Add SonarQube Helm repository
        run: |
          helm repo add sonarqube \
            https://SonarSource.github.io/helm-chart-sonarqube
          helm repo update
