name: Setup SonarQube Infrastructure (PVC FIXED)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/workflows/sonarqube-setup.yaml"]

env:
  PROJECT_ID: primordial-port-462408-q7
  CLUSTER_NAME: primordial-port-462408-q7-gke-cluster
  CLUSTER_REGION: europe-west9
  POSTGRES_VERSION: "13"
  SONARQUBE_CHART_VERSION: "2025.3.0"
  POSTGRES_STORAGE: "10Gi"
  SONARQUBE_STORAGE: "10Gi"

jobs:
  deploy-sonarqube:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    outputs:
      sonar_url: ${{ steps.get-url.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Add Helm repositories and update
        run: |
          echo " Mise à jour des repositories Helm..."
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
          helm repo update

      - name: Create namespace and cleanup old resources
        run: |
          echo " Nettoyage et création du namespace..."
          kubectl create ns sonarqube --dry-run=client -o yaml | kubectl apply -f -
          
          # Nettoyer les anciens déploiements et PVCs
          echo "Suppression des anciens déploiements..."
          kubectl delete deployment postgres sonarqube --ignore-not-found=true -n sonarqube
          
          echo "Suppression des anciens PVCs..."
          kubectl delete pvc postgres-pv-claim postgres-pv-claim-new sonarqube-data sonarqube-data-new --ignore-not-found=true -n sonarqube
          
          echo "Attente du nettoyage..."
          sleep 30
          
          echo "État après nettoyage:"
          kubectl get pvc -n sonarqube || echo "Aucun PVC trouvé"

      - name: Deploy PostgreSQL with unique PVC name
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          # Générer un nom unique pour le PVC
          TIMESTAMP=$(date +%s)
          PVC_NAME="postgres-pvc-${TIMESTAMP}"
          
          echo " Création du PVC PostgreSQL: $PVC_NAME"
          
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: $PVC_NAME
            namespace: sonarqube
            labels:
              app: postgres
              timestamp: "$TIMESTAMP"
          spec:
            accessModes: [ReadWriteOnce]
            resources:
              requests:
                storage: ${{ env.POSTGRES_STORAGE }}
            storageClassName: standard-rwo
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secret
            namespace: sonarqube
          type: Opaque
          data:
            postgres-password: $(echo -n "$POSTGRES_PASSWORD" | base64 -w0)
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: postgres
            namespace: sonarqube
            labels:
              app: postgres
              timestamp: "$TIMESTAMP"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: postgres
            template:
              metadata:
                labels:
                  app: postgres
                  timestamp: "$TIMESTAMP"
              spec:
                containers:
                - name: postgres
                  image: postgres:${{ env.POSTGRES_VERSION }}
                  env:
                  - name: POSTGRES_DB
                    value: sonarqube
                  - name: POSTGRES_USER
                    value: sonarqube
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: postgres-secret
                        key: postgres-password
                  - name: PGDATA
                    value: /var/lib/postgresql/data/pgdata
                  ports:
                  - containerPort: 5432
                  volumeMounts:
                  - name: postgres-storage
                    mountPath: /var/lib/postgresql/data
                  readinessProbe:
                    exec:
                      command: ["pg_isready", "-U", "sonarqube", "-d", "sonarqube"]
                    initialDelaySeconds: 15
                    periodSeconds: 5
                    timeoutSeconds: 3
                    failureThreshold: 6
                  livenessProbe:
                    exec:
                      command: ["pg_isready", "-U", "sonarqube", "-d", "sonarqube"]
                    initialDelaySeconds: 30
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 3
                  startupProbe:
                    exec:
                      command: ["pg_isready", "-U", "sonarqube", "-d", "sonarqube"]
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    timeoutSeconds: 3
                    failureThreshold: 20
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "256Mi"
                      cpu: "200m"
                volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: $PVC_NAME
                securityContext:
                  fsGroup: 999
                  runAsUser: 999
                  runAsGroup: 999
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: postgres
            namespace: sonarqube
            labels:
              app: postgres
          spec:
            ports:
            - port: 5432
            selector:
              app: postgres
          EOF
          
          # Sauvegarder le nom du PVC pour les étapes suivantes
          echo "PVC_NAME=$PVC_NAME" >> $GITHUB_ENV

      - name: Wait for PostgreSQL PVC with enhanced monitoring
        run: |
          echo " Attente du PVC PostgreSQL: $PVC_NAME"
          
          # Vérifier l'état initial
          echo "=== État initial ==="
          kubectl get pvc -n sonarqube
          kubectl get storageclass
          
          # Attendre que le PVC soit lié avec monitoring détaillé
          for i in {1..20}; do
            echo "--- Vérification PVC $i/20 ---"
            
            PVC_STATUS=$(kubectl get pvc $PVC_NAME -n sonarqube -o jsonpath='{.status.phase}' 2>/dev/null || echo "NotFound")
            echo "Statut PVC: $PVC_STATUS"
            
            if [ "$PVC_STATUS" = "Bound" ]; then
              echo " PVC $PVC_NAME est lié!"
              kubectl describe pvc $PVC_NAME -n sonarqube
              break
            fi
            
            if [ $i -eq 20 ]; then
              echo " Timeout PVC après 10 minutes"
              echo "=== Diagnostic PVC ==="
              kubectl describe pvc $PVC_NAME -n sonarqube
              kubectl get events -n sonarqube --sort-by='.lastTimestamp' | tail -10
              exit 1
            fi
            
            # Afficher les détails toutes les 5 tentatives
            if [ $((i % 5)) -eq 0 ]; then
              echo "=== Détails PVC ==="
              kubectl describe pvc $PVC_NAME -n sonarqube | tail -10
              echo "=== Événements récents ==="
              kubectl get events -n sonarqube --sort-by='.lastTimestamp' | tail -5
            fi
            
            sleep 30
          done

      - name: Wait for PostgreSQL Pod with enhanced monitoring
        run: |
          echo " Attente du pod PostgreSQL..."
          
          # Surveiller le démarrage du pod
          for i in {1..30}; do
            echo "--- Vérification Pod $i/30 ---"
            kubectl get pods -n sonarqube -l app=postgres -o wide
            
            if kubectl get pods -n sonarqube -l app=postgres | grep -q "1/1.*Running"; then
              echo " PostgreSQL est prêt!"
              break
            fi
            
            # Vérifier s'il y a des erreurs
            POD_NAME=$(kubectl get pods -n sonarqube -l app=postgres -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
            if [ -n "$POD_NAME" ]; then
              POD_STATUS=$(kubectl get pod $POD_NAME -n sonarqube -o jsonpath='{.status.phase}')
              echo "Statut Pod: $POD_STATUS"
              
              # Afficher les logs si le pod existe
              if [ "$POD_STATUS" != "Pending" ] && [ $((i % 5)) -eq 0 ]; then
                echo "=== Logs PostgreSQL ==="
                kubectl logs $POD_NAME -n sonarqube --tail=5 2>/dev/null || echo "Pas de logs encore"
              fi
            fi
            
            if [ $i -eq 30 ]; then
              echo " Timeout PostgreSQL après 10 minutes"
              kubectl describe pods -n sonarqube -l app=postgres
              kubectl logs -l app=postgres -n sonarqube --tail=20 2>/dev/null || echo "Pas de logs"
              exit 1
            fi
            
            sleep 20
          done
          
          # Test de connexion final
          echo " Test de connexion PostgreSQL..."
          kubectl exec -n sonarqube deployment/postgres -- pg_isready -U sonarqube -d sonarqube

      - name: Deploy SonarQube with corrected version
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo " Déploiement SonarQube version ${{ env.SONARQUBE_CHART_VERSION }}..."
          
          helm upgrade --install sonarqube sonarqube/sonarqube \
            --namespace sonarqube \
            --version ${{ env.SONARQUBE_CHART_VERSION }} \
            --set postgresql.enabled=false \
            --set postgresql.postgresqlServer=postgres.sonarqube.svc.cluster.local \
            --set postgresql.postgresqlDatabase=sonarqube \
            --set postgresql.postgresqlUsername=sonarqube \
            --set postgresql.postgresqlPassword="$POSTGRES_PASSWORD" \
            --set persistence.enabled=true \
            --set persistence.size=${{ env.SONARQUBE_STORAGE }} \
            --set service.type=LoadBalancer \
            --set resources.requests.memory=1Gi \
            --set resources.requests.cpu=500m \
            --set resources.limits.memory=2Gi \
            --set resources.limits.cpu=1000m \
            --set sonarProperties."sonar\.es\.bootstrap\.checks\.disable"=true \
            --timeout 15m \
            --wait

      - name: Wait for SonarQube to be ready
        run: |
          echo " Attente de SonarQube..."
          
          # Attendre que le service soit disponible
          kubectl wait --for=condition=available deployment/sonarqube-sonarqube -n sonarqube --timeout=900s
          
          # Attendre que l'IP externe soit assignée
          echo "Attente de l'IP externe..."
          for i in {1..20}; do
            SONAR_IP=$(kubectl get svc sonarqube-sonarqube -n sonarqube -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
            if [ -n "$SONAR_IP" ]; then
              echo " IP externe assignée: $SONAR_IP"
              break
            fi
            echo "Attente de l'IP externe... ($i/20)"
            sleep 15
          done

      - name: Get SonarQube URL and test connectivity
        id: get-url
        run: |
          SONAR_IP=$(kubectl get svc sonarqube-sonarqube -n sonarqube -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          SONAR_URL="http://$SONAR_IP:9000"
          
          echo "url=$SONAR_URL" >> $GITHUB_OUTPUT
          echo " SonarQube URL: $SONAR_URL"
          
          # Test de connectivité
          echo " Test de connectivité..."
          for i in {1..20}; do
            if curl -sSf "$SONAR_URL/api/system/status" | grep -q "UP\|STARTING"; then
              echo " SonarQube répond!"
              break
            fi
            echo "Attente de SonarQube... ($i/20)"
            sleep 30
          done

  configure-sonarqube:
    runs-on: ubuntu-latest
    needs: deploy-sonarqube
    if: success()
    steps:
      - name: Configure projects and admin password
        env:
          SONAR_URL: ${{ needs.deploy-sonarqube.outputs.sonar_url }}
          SONAR_ADMIN_PASSWORD: ${{ secrets.SONAR_ADMIN_PASSWORD }}
        run: |
          echo " Configuration de SonarQube..."
          
          # Attendre que SonarQube soit complètement prêt
          for i in {1..30}; do
            if curl -sSf "$SONAR_URL/api/system/health" | grep -q "GREEN"; then
              echo " SonarQube est prêt pour la configuration"
              break
            fi
            echo "Attente que SonarQube soit prêt... ($i/30)"
            sleep 20
          done

          # Changer le mot de passe admin
          echo " Changement du mot de passe admin..."
          curl -X POST "$SONAR_URL/api/users/change_password" \
            -u "admin:admin" \
            -d "login=admin&password=$SONAR_ADMIN_PASSWORD&previousPassword=admin" \
            --fail-with-body || echo " Mot de passe déjà changé ou erreur"

          # Créer les projets
          echo " Création des projets..."
          curl -X POST "$SONAR_URL/api/projects/create" \
            -u "admin:$SONAR_ADMIN_PASSWORD" \
            -d "name=Frontend&project=frontend&visibility=public" \
            --fail-with-body || echo " Projet frontend existe déjà"
          
          curl -X POST "$SONAR_URL/api/projects/create" \
            -u "admin:$SONAR_ADMIN_PASSWORD" \
            -d "name=Backend&project=backend&visibility=public" \
            --fail-with-body || echo " Projet backend existe déjà"
          
          echo " Configuration terminée!"
          echo " SonarQube accessible à: $SONAR_URL"
          echo " Identifiants: admin / $SONAR_ADMIN_PASSWORD"